### ISSUE TITLE
Resource code completion should list input resources in pipeline

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#189]
In a pipeline users could add a resource and IJ should be smart enough to suggest all resources which exists in the pipeline

Example 
```
- name: first-create-file
      taskRef:
        name: create-readme-file
      resources:
        outputs:
          - name: workspace
            resource: <--- code completion here
```
