### ISSUE TITLE
Start pipeline wizard does not support finally tasks

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#204]
Finally tasks for a pipeline are not available through the start wizard::

Pipeline:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  resources:
  - name: pipeline-resource-type
    type: git
  tasks:
  - name: foo
    taskRef:
      kind: Task
      name: build-app
  finally:
    - name: cleanup
      taskRef:
        kind: Task
        name: echo

```

Wizard page:

![image](https://user-images.githubusercontent.com/695993/92744394-be76aa00-f381-11ea-9689-85bdd01e4efc.png)
