### ISSUE TITLE
Tekton trigger 0.9.0 changes how binding must be defined

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#252]
An extract from the 0.9.0 trigger release 
```
Adds support for name/value embedded Bindings (#768)

TriggerBindings can now be embedded by using just name/value fields inside a Trigger or a EventListener.

BREAKING CHANGE: With this change, users cannot specify both name and ref
for a single binding. Use ref to refer to a TriggerBinding resource and
name for embedded bindings.
```

```
# NEW SYNTAX:

bindings:
- ref: some-name
- name: commit_id # embedded binding
  value: "$(body.head_commit_id)"

# OLD SYNTAX:
bindings:
- name: some-name
  spec:
    params:
    - name: commit_id # embedded binding
      value: "$(body.head_commit_id)
```
This breaks our `Add Trigger` action + snippets
