### ISSUE TITLE
Create Pipeline: does not show, when there is an error in pipeline

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/intellij-tekton#274]
(I have followed this turorial for creating pipeline: https://github.com/openshift/pipelines-tutorial#deploy-sample-application)

When I try to create new pipeline with error:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-build
  namespace: pipelines-tutorial
spec:
  params:
    - description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: master
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - description: image to be build from the code
      name: IMAGE
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-image
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
```

No error is shown and also pipeline is not pushed.
When I add at the end:
```
  workspaces:
    - name: shared-workspace
```
Pipeline is correct and correctly pushed.
