### ISSUE TITLE
Make the plugin work wth AWS auth

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#302]
By having a kubeconfig like this 

```
- cluster:
    certificate-authority-data: LONG LINK
    server: API URL
  name: arn:aws:eks:us-west-2:redacted:cluster/core
 
.....

- name: arn:aws:eks:us-west-2:redacted:cluster/prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - core
      command: aws
      env:
      - name: AWS_PROFILE
        value: strateos

```

the plugin is not able to connect to the cluster.

Issues related to this

- https://github.com/fabric8io/kubernetes-client/issues/2388
- https://github.com/fabric8io/kubernetes-client/pull/1224
