### ISSUE TITLE
Error when starting a task in debug with numbers as inputs

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#518]
When starting a taskrun in debug everything works fine but when i start a task in debug i got 
```
add-task in namespace tekton-pipelines failed to start
Failure executing: POST at: https://api.ci-ln-s5gy71k-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443/apis/tekton.dev/v1beta1/namespaces/tekton-pipelines/taskruns. Message: admission webhook 
"webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal 
number into Go struct field Param.spec.params.value of type []string. Received status: Status(apiVersion=v1, code=400, details=null, 
kind=Status, message=admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode 
incoming new object: json: cannot unmarshal number into Go struct field Param.spec.params.value of type []string, 
metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), 
reason=BadRequest, status=Failure, additionalProperties={}).

```
tekton version
```
Pipeline version: v0.31.0
```

oc  version
```
Client Version: 4.8.5
Server Version: 4.9.0
Kubernetes Version: v1.22.0-rc.0+894a78b
```

task used for testing
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: add-task
spec:
  params:
  - description: the first operand
    name: first
    type: string
  - description: the second operand
    name: second
    type: string
  results:
  - description: the sum of the first and second operand
    name: sum
  steps:
  - args:
    - echo -n $((${OP1}+${OP2})) | tee $(results.sum.path);
    command:
    - /bin/sh
    - -c
    env:
    - name: OP1
      value: $(params.first)
    - name: OP2
      value: $(params.second)
    image: alpine
    name: add
    resources: {}
  - image: fedora
    name: echo
    resources: {}
    script: npm run not-exists

```
