### ISSUE TITLE
Add snippets for conditions

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#80]
When editing a YAML, user should be able to generate snippets for conditions using code completion. The snippets are

Condition type
Condition reference in a taskref e.g.

```
- name: list-pipeline-repo-files-1
      taskRef:
        name: list-pipeline-repo-files
      conditions:
        - conditionRef: "verify-no-file-exists-without-resource"
          params:
            - name: "path"
              value: "$(params.path)"
```
